//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slip39.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slip39.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandon
        ///ability
        ///able
        ///about
        ///above
        ///absent
        ///absorb
        ///abstract
        ///absurd
        ///abuse
        ///access
        ///accident
        ///account
        ///accuse
        ///achieve
        ///acid
        ///acoustic
        ///acquire
        ///across
        ///act
        ///action
        ///actor
        ///actress
        ///actual
        ///adapt
        ///add
        ///addict
        ///address
        ///adjust
        ///admit
        ///adult
        ///advance
        ///advice
        ///aerobic
        ///affair
        ///afford
        ///afraid
        ///again
        ///age
        ///agent
        ///agree
        ///ahead
        ///aim
        ///air
        ///airport
        ///aisle
        ///alarm
        ///album
        ///alcohol
        ///alert
        ///alien
        ///all
        ///alley
        ///allow
        ///almost
        ///alone
        ///alpha
        ///already
        ///also
        ///alter
        ///always
        ///amateur
        ///amazing
        ///among
        ///amount
        ///amused
        ///analyst
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bip39WordList {
            get {
                return ResourceManager.GetString("Bip39WordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to academic
        ///acid
        ///acne
        ///acquire
        ///acrobat
        ///activity
        ///actress
        ///adapt
        ///adequate
        ///adjust
        ///admit
        ///adorn
        ///adult
        ///advance
        ///advocate
        ///afraid
        ///again
        ///agency
        ///agree
        ///aide
        ///aircraft
        ///airline
        ///airport
        ///ajar
        ///alarm
        ///album
        ///alcohol
        ///alien
        ///alive
        ///alpha
        ///already
        ///alto
        ///aluminum
        ///always
        ///amazing
        ///ambition
        ///amount
        ///amuse
        ///analysis
        ///anatomy
        ///ancestor
        ///ancient
        ///angel
        ///angry
        ///animal
        ///answer
        ///antenna
        ///anxiety
        ///apart
        ///aquatic
        ///arcade
        ///arena
        ///argue
        ///armed
        ///artist
        ///artwork
        ///aspect
        ///auction
        ///august
        ///aunt
        ///average
        ///aviation
        ///avoid
        ///aw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Slip39WordList {
            get {
                return ResourceManager.GetString("Slip39WordList", resourceCulture);
            }
        }
    }
}
